### ISSUE TITLE
Event handler, e not used

### ISSUE THREAD

**Issue by geraldMaboshe** [geraldMaboshe/todoApp#4]
@OlivierJM  the event handler, e that you've passed as a parameter in the markComplete method has not been used. Could there be a reason why it is there?

**Comment by OlivierJM** [comment]
Yes there is a reason, 
The id is passed in Todo component as a second argument, that is why the event is not used because what we want is the id

**Comment by geraldMaboshe** [comment]
I get it

**Comment by OlivierJM** [comment]
awesome
